name: Firebase Hosting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Google Cloud via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/780708298005/locations/global/workloadIdentityPools/github-pool/providers/github-oidc"
          service_account: "github-action-1076248736@veas-website-01-35691.iam.gserviceaccount.com"

      - name: Enable Firebase Web Frameworks support
        run: firebase experiments:enable webframeworks

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project veas-website-01-35691
