name: Deploy to Firebase Hosting with OIDC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Google Cloud via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/780708298005/locations/global/workloadIdentityPools/github-pool/providers/github-oidc"
          service_account: "github-action-1076248736@veas-website-01-35691.iam.gserviceaccount.com"

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project veas-website-01-35691
